# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160407_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=False, verbose_name=b'Like'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=False, verbose_name=b'Dislike'),
        ),
    ]
