# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_glance'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
