# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='had_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='had_like',
            field=models.BooleanField(default=False),
        ),
    ]
